### ISSUE TITLE
How to active Comment section!

### ISSUE THREAD

**Issue by manii-stack** [abrudtkuhl/WordPressSharp#106]
Hi guys
When I send a post to WordPress via wordpresssharp, by default comment section is disabled. how can enable it by default?

**Comment by manii-stack** [comment]
anyone can help me?

**Comment by abrudtkuhl** [comment]
Hi @mohammad983 - I think you want the comment status field set to "open".

'comment_status'
(string) Post comment enabled status. Accepts 'open' or 'closed'.

https://developer.wordpress.org/reference/classes/wp_xmlrpc_server/wp_newpost/

**Comment by manii-stack** [comment]
it's exactly what I want. thanks.
