### ISSUE TITLE
wp.NewPost Terms/Categories returns error 401

### ISSUE THREAD

**Issue by weltmeyer** [abrudtkuhl/WordPressSharp#22]
var testTerm= client.GetTerms(...).First();
post.Terms=new []{testTerm};
When creating a new post with NewPost(Post post) it throws an error 401.
It seems like the format of Terms is wrong for new post.

**Comment by alldjay** [comment]
> Term[] t = new Term[1];
 t[0] = client.GetTerm("category",4); // 4 is an existing category that was already being used...

It work for me, but how to set several existing categories in post? 
Example please...
Thanks.

**Comment by abrudtkuhl** [comment]
See how it works here https://github.com/abrudtkuhl/WordPressSharp/issues/68#issuecomment-321923121
