### ISSUE TITLE
How publish new post

### ISSUE THREAD

**Issue by Radzhab** [abrudtkuhl/WordPressSharp#30]
I wnat add param bool publish in true. Where i can make it? New posts automatic go to draft

**Comment by abrudtkuhl** [comment]
You just need to put 'publish' in the status property of the post object. I can send you an example if needed

**Comment by Radzhab** [comment]
please send me example)

**Comment by Radzhab** [comment]
i think all peoples want full example of this lib. I want only one example in this repository)

**Comment by Radzhab** [comment]
??? what about example

**Comment by abrudtkuhl** [comment]
Patience young Jedi

**Comment by Radzhab** [comment]
OK

**Comment by abrudtkuhl** [comment]
Blog post coming today

**Comment by abrudtkuhl** [comment]
@Radzhab looks like I've had an example on the project page the whole time! http://abrudtkuhl.github.io/WordPressSharp/ But not quite addressing your specific question on adding a status.

Here's a bit more in depth post describing how to publish a new post or page in WordPress. If you have any questions further on publishing a post/page please leave a response there. http://brudtkuhl.com/using-wordpresssharp-publish-post/

**Comment by Radzhab** [comment]
its make scheduled type of post.

**Comment by abrudtkuhl** [comment]
I'm not sure I understand your question

**Comment by Radzhab** [comment]
![4ec5930425](https://cloud.githubusercontent.com/assets/2556411/5925275/69a55cda-a673-11e4-8475-2c37f65be8ea.jpg)

**Comment by Radzhab** [comment]
![de3e287d46](https://cloud.githubusercontent.com/assets/2556411/5925289/854aa832-a673-11e4-9723-86cc82c3b63b.jpg)

**Comment by abrudtkuhl** [comment]
ahh okay. I wonder if your DateTime.Now where your app is running is
different than the server time where WordPress is running

Andy Brudtkuhl
@abrudtkuhl <http://twitter.com/abrudtkuhl>

**Comment by Radzhab** [comment]
thx man!) From Russia with love
