### ISSUE TITLE
NewPost fails with no Terms

### ISSUE THREAD

**Issue by emumanu** [abrudtkuhl/WordPressSharp#31]
Hello,

it's nice to see this library is getting better.

However, with the latest version I got a null reference exception when creating a new post without Terms, because post.Terms is null in NewPost

var termTaxes = post.Terms.GroupBy(t => t.Taxonomy);

The same happens in EditPost

**Comment by abrudtkuhl** [comment]
Thanks @emumanu! 

This may have happened in one of the latest pull requests. I will look into it asap but feel free to fix it and submit a pull request!

A goal in the next several months is to add a set of unit tests in the project so we can do regression tests before merging in pull requests.

Thanks!

**Comment by tekguy** [comment]
@abrudtkuhl @emumanu  I fixed it on the NewPost. I will look into EditPost see pull request 42.

Thanks!
