### ISSUE TITLE
EditPost fails

### ISSUE THREAD

**Issue by emumanu** [abrudtkuhl/WordPressSharp#32]
Hello,

EditPost fails in WP 4.1:

An unhandled exception of type 'CookComputing.XmlRpc.XmlRpcTypeMismatchException' occurred in CookComputing.XmlRpcV2.dll

Additional information: response contains array value where string expected [response : struct mapped to type Post : member FeaturedImageId mapped to type String]

it seems that Media Item is not implemented. Are there plans for this?

Thanks

**Comment by abrudtkuhl** [comment]
Yes. I know we have an issue for uploadItem. Thanks will look into this... feel free to fix and submit PR if you dont want to wait! :)

**Comment by abrudtkuhl** [comment]
Closed thanks to @KeesCBakker
