### ISSUE TITLE
GetPosts doesn't work

### ISSUE THREAD

**Issue by carminexx** [abrudtkuhl/WordPressSharp#33]
Hi,
I'm trying to retrieve all posts with the GetPosts function. I'm sure the connection is ok, because I also used newPost and newTerm without problems.
Instead, when I call getPosts, I got this exception:

response contains array value where string expected [response : array mapped to type Post[] : element 0 : struct mapped to type Post : member FeaturedImageId mapped to type String]

I'm passing just "null" to PostFilter, since I don't need to filter posts, and the post filter argument is optional in Wordpress XML-RPC API.

**Comment by abrudtkuhl** [comment]
yea that should be optional. I'll take a look. I think GetPosts was
incomplete will check open issues on progress

Andy Brudtkuhl
@abrudtkuhl <http://twitter.com/abrudtkuhl>

**Comment by avishnyakov** [comment]
Same same. 

GetPosts() is needed to check if post/page was created, so that we will create a new or update existing one. Is there any work around for that?

How can I help to fix this?

**Comment by KeesCBakker** [comment]
Any news on a fix?

**Comment by KeesCBakker** [comment]
Removing _FeaturedImageId_ from _Post_ seems to "fix" the error". Something is wrong with the mapping there.

**Comment by abrudtkuhl** [comment]
Thanks for the pointer! If you can figure out the proper mapping, please
submit the fix via a Pull Request! Otherwise hoping to jump back into this
project this week

Andy Brudtkuhl
@abrudtkuhl <http://twitter.com/abrudtkuhl>

**Comment by abrudtkuhl** [comment]
Thanks for helping squash these bugs!
