### ISSUE TITLE
Cant submit newPost without Tags/Taxonomies, ArgNullExcp

### ISSUE THREAD

**Issue by tayfunyasar** [abrudtkuhl/WordPressSharp#41]
Cant submit newPost with

 Post post = setPost(1, title, content);
      post.CustomFields = getCustomFields();
      using (var client = getWordpressClient())
      {
        return client.NewPost(post);
      }

error: http://a.disquscdn.com/get?url=http%3A%2F%2Fi.hizliresim.com%2FWVJ1oP.png&key=yp1qGdi9DWiFpv5NFagx0A&w=800&h=165

**Comment by abrudtkuhl** [comment]
@tayfunyasar  can you post a full code snippet on Gist?

See how to (Using WordPressSharp to publish a new post)[http://brudtkuhl.com/using-wordpresssharp-publish-post/]
