### ISSUE TITLE
XmlRpcFaultException in WordPressClient.cs

### ISSUE THREAD

**Issue by tayfunyasar** [abrudtkuhl/WordPressSharp#43]
WordPressSharpHelper.cs 
http://paste.ubuntu.com/10863863/

my postCode

Helper.WordPressSharpHelper.postToWordpress(title, iframe, "603");

error at 185.th line,
\Projects\WordPressSharp\WordPressClient.cs

Exception is:
An unhandled exception of type 'CookComputing.XmlRpc.XmlRpcFaultException' occurred in CookComputing.XmlRpcV2.dll

Additional information: Server returned a fault exception: [401]

**Comment by abrudtkuhl** [comment]
@tayfunyasar I think that is a [401 HTTP Status Code](http://stackoverflow.com/a/6937030) - which means you are making an unauthorized request. I'd make sure your username and password are being set correctly (and are valid)

**Comment by tayfunyasar** [comment]
I know the meaning. I can send newPost with JoeBlogs but cant send with WordpressSharp. With same username, url, password..

**Comment by KeesCBakker** [comment]
You might want to debug the XmlRpc by adding a logger to the project. I've did this once like this:

```
var client = new WordPressClient();

RequestResponseLogger logger = new RequestResponseLogger();
logger.Directory = "Data";
client.WordPressService.AttachLogger(logger);
```

**Comment by nicholaswilson05** [comment]
I'm trying to debug the XmlRpc as well, like you suggested above, but there's no "AttachLogger" method on WordPressService. Am I missing something? Thanks.

**Comment by nicholaswilson05** [comment]
Nevermind - Looks like I had an old version from the Nuget package.

**Comment by abrudtkuhl** [comment]
Yea nuget pkg needs updated. Will do that today and look into myget to automatically build  the pkg from latest in github

**Comment by KeesCBakker** [comment]
This project is under nuget?

**Comment by nicholaswilson05** [comment]
It is, but like we were saying, it's not up to date. I think it was last updated in January of this year.
