### ISSUE TITLE
How to add thumbnail image into newPost

### ISSUE THREAD

**Issue by tayfunyasar** [abrudtkuhl/WordPressSharp#44]
I've posted alotof post via testmethod. Now trying to post with thumb image.

I modified the method like this.

public void CreatePost()
    {
      using (var client = CreateDefaultClient())
      {
        string post_thumbnail = "http://pbs.twimg.com/profile_images/xxx/xxx.jpeg";
        var post = new Post
        {
          PostType = "post", // "post" or "page"
          Title = "Test Title",
          Content = "Test",
          PublishDateTime = DateTime.Now,
          Status = "publish" // "draft" or "publish"
        };
        post.CustomFields = new[] {
                new CustomField{
                  Key="_thumbnail_id",
                  Value="603"
                },
                 new CustomField() { 
                    Key = "_thumbnail_id", 
                    Value = post_thumbnail
                } 
                ,
                  new CustomField() { 
                    Key = "post_thumbnail", 
                    Value = post_thumbnail
                } 
                ,
                     new CustomField() { 
                    Key = "post-thumbnail", 
                    Value = post_thumbnail
                }  ,
                     new CustomField() { 
                    Key = "post-thumbnails", 
                    Value = post_thumbnail
                } ,
                     new CustomField() { 
                    Key = "thumbnail_id", 
                    Value = post_thumbnail
                } 
              };
        client.NewPost(post);
      }

What is the key value for thumb?

**Comment by tayfunyasar** [comment]
I've tried also this

 post.CustomFields = new[] {
                new CustomField{
                  Key="_thumbnail_id",
                  Value="603"
                },
                 new CustomField() { 
                    Key = "_wp_attached_file", 
                    Value = "2015/04/IMG-20150408-WA0000-Copy.jpg"
                } 
              };
        post.MediaItems = new[] {
          new MediaItem{
           Thumbnail="2015/04/IMG-20150408-WA0000-Copy.jpg"
          }
    new MediaItem{
           Id="603"
          }
        };

**Comment by KeesCBakker** [comment]
I'm doing the following:

```
WordPressClient client = ...;
Post post = ...;

var url = "http://lorempixel.com/400/200/sports/";
var name = Path.GetFileName(url);

Data data = null;

using (WebClient wc = new WebClient())
{
	data = new Data()
	{
		Name = Path.GetFileName(url),
		Bits = wc.DownloadData(url),
		Type = wc.ResponseHeaders["content-type"]
	};
}

post.FeaturedImageId = client.UploadFile(data).Id;
```

**Comment by tayfunyasar** [comment]
No way.. Thanks @KeesCBakker !

**Comment by KeesCBakker** [comment]
Even easier with the new CreateFromUrl method:

```
WordPressClient client = ...;
Post post = ...;

var data = Data.CreateFromUrl("http://lorempixel.com/400/200/sports/");
post.FeaturedImageId = client.UploadFile(data).Id;
```

**Comment by manii-stack** [comment]
its work for me
```
var url = "http://lorempixel.com/400/200/sports/";
var name = Path.GetFileName(url);

Data data = null;

using (WebClient wc = new WebClient())
{
    data = new Data()
    {
        Name = Path.GetFileName(url),
        Bits = wc.DownloadData(url),
        Type = wc.ResponseHeaders["content-type"]
    };
}

post.FeaturedImageId = client.UploadFile(data).Id;
```

it gets me this error!
`Error	CS1061	'XDocument' does not contain a definition for 'CreateFromUrl' and no extension method 'CreateFromUrl' accepting a first argument of type 'XDocument' could be found (are you missing a using directive or an assembly reference?)`
Could you help me how can I fix it?
