### ISSUE TITLE
Relation btw Post and Category

### ISSUE THREAD

**Issue by tayfunyasar** [abrudtkuhl/WordPressSharp#48]
How to set Post's Category?

i cant find categoryId in "Post" class.

Thanks

**Comment by KeesCBakker** [comment]
You can create a Term of the right type and as it to the Terms. Categories and Tags work through terms.

**Comment by KeesCBakker** [comment]
* add

**Comment by tayfunyasar** [comment]
How? Cant figure out

**Comment by KeesCBakker** [comment]
I use the following code:

```
var post = ...;

//create the keyword
var keyword = new Term
{
	Name = h,
	Slug = h,
	Taxonomy = "post_tag"
};

//save it
keyword.Id = client.NewTerm(keyword);

//create a terms list
var terms = new List<Term>();
terms.Add(keyword);

//add it
post.Terms = terms.ToArray();
```

Hope you'll get somewhere with it.

**Comment by KeesCBakker** [comment]
Both tags and categories are expressed as terms.

**Comment by tayfunyasar** [comment]
Thanks! it works.

**Comment by KeesCBakker** [comment]
Great to hear. Sorry for the late reply. Has been pretty busy lately.

**Comment by cenaav** [comment]
Sorry! would you help me? i can't post with terms.


```
Term keyword = WPClient.GetTerm("category", 2);
var terms = new List<Term>();
terms.Add(keyword);
var post = new Post();
post.Title = "TEST";
post.Content = "THIS IS TEST";
post.PostType = "post";
post.Status = "publish";
post.PublishDateTime = DateTime.Now;
post.Terms = terms.ToArray();
string res = WPClient.NewPost(post);
```


but an error happen.

401 
taxonomy in terms or terms_names is not supported by this post type. 

any suggestion ?

**Comment by 1428245421** [comment]
`  var client = new WordPressClient(new WordPressSiteConfig
            {
                BaseUrl = "http://localhost/wordpress",
                Username = "123456",
                Password = "123456",
                BlogId = 1
            });
            var post = new Post
            {
                Title = "hello world",
                PostType = "post",
                PublishDateTime = DateTime.Now,
                Content = "hello world",
               // Terms = new Term[] { t },
                Status = "publish",
                //评论状态    CommentStatus

            };

            //create the keyword
            var keyword = new Term
            {
                Name = "My amazing new category",
                Slug = "miauw",
                Taxonomy = "category"
                //save it
            };

           
           keyword.Id = client.NewTerm(keyword);
            //create a terms list(创建了列表)


            var terms = new List<Term>();
          terms.Add(keyword);

            //add it
            post.Terms = terms.ToArray();
            MessageBox.Show(client.NewPost(post));`




I succeeded in creating a category, but I don't know how to make categories for new articles.

**Comment by abrudtkuhl** [comment]
@1428245421 https://github.com/abrudtkuhl/WordPressSharp/issues/48#issuecomment-105643517
