### ISSUE TITLE
getPost throwing except (ParentId expected to be int)

### ISSUE THREAD

**Issue by setiri** [abrudtkuhl/WordPressSharp#50]
Getting this exception: 
An unhandled exception of type 'CookComputing.XmlRpc.XmlRpcTypeMismatchException' occurred in CookComputing.XmlRpcV2.dll

Additional information: response contains string value where integer expected [response : struct mapped to type Post : member ParentId mapped to type Int32]

I'm looking in the xml returned and the closest thing to a Parent Id is this: 

<member><name>post_parent</name><value><string>0</string></value></member>

As well as this for every tag defined on the post: 
<member><name>parent</name><value><string>0</string></value></member>

So it seems that these are defining their values as string, but still actually contain zeros (int) values in them. 

Any solutions/workarounds?

**Comment by setiri** [comment]
I think this might be fixed in the latest, but it seems nuget version is outdated now

**Comment by abrudtkuhl** [comment]
The nuget version is out of date. Working on getting that automated

Andy Brudtkuhl
@abrudtkuhl <http://twitter.com/abrudtkuhl>

**Comment by setiri** [comment]
Yes, I figured this out last night. pulled the source and rebuilt it, works fine now.

**Comment by nathanchere** [comment]
Any chance the nuget version might be updated in the foreseeable future?

**Comment by abrudtkuhl** [comment]
yes i will try to run a build over the weekend and deploy it. thanks

Andy Brudtkuhl
@abrudtkuhl <http://twitter.com/abrudtkuhl>

**Comment by lszomoru** [comment]
Any update on publishing and updated package to Nuget? Thanks!

**Comment by abrudtkuhl** [comment]
FYI @lszomoru  the nuget package is updated https://www.nuget.org/packages/WordPressSharp/
