### ISSUE TITLE
Method not allowed.

### ISSUE THREAD

**Issue by Seekeer** [abrudtkuhl/WordPressSharp#53]
I am trying to execute following code:

```
        var config = new WordPressSharp.WordPressSiteConfig();
        config.BaseUrl = "http://dasfoland.wordpress.com";
        config.Username = user;
        config.Password =  pass;
        config.BlogId = id;
       _client = new WordPressClient(config);
       var posts = _client.GetPosts(filter);
```

And each time I get following exception:

An unhandled exception of type 'CookComputing.XmlRpc.XmlRpcServerException' occurred in CookComputing.XmlRpcV2.dll
Additional information: Method Not Allowed

What am I doing wrong?

**Comment by abrudtkuhl** [comment]
I think for wordpress.com sites you need to add /xmlrpc.php to your base url

**Comment by tayfunyasar** [comment]
You cant use xmlrpc api in wordpress.com subdomains. you need host.

**Comment by Seekeer** [comment]
>You cant use xmlrpc api in wordpress.com subdomains. you need host.
Ok, thanks for info. Are there any way to get free wordpress blog to test XMLRPC API?

**Comment by abrudtkuhl** [comment]
Run WP locally

**Comment by Joe118** [comment]
I don't think this is correct, I was able to connect to dojotest1.wordpress.com with the POSSIBLE WP API client, but WordPressSharp causes an exception... I experienced the exception with NewPost and GetPosts in WordPressSharp but not with POSSIBLE. Of course I'd rather use WordPressSharp because it is more updated and complete.

**Comment by Joe118** [comment]
I also hit this and the problem is present in POSSIBLE XmlRpc as well as in WordPressSharp. So it does seem to be a limitation of wordpress.com :(

**Comment by mostafa901** [comment]
it is not working for me as well. :( ... any idea to resolve this?

`  WordPressSharp.WordPressSiteConfig wpcon = new WordPressSharp.WordPressSiteConfig();
            wpcon.Username = "myuser";
            wpcon.Password = "mypass";
            wpcon.BaseUrl = "http://moustafakh.wordpress.com/";
            wpcon.BlogId = 1;

            WordPressSharp.WordPressClient wpc = new WordPressSharp.WordPressClient(wpcon);
            Post pos = new Post();
            pos.Title = "My title";
            pos.Content = "this is a test for the content";
            pos.PostType = WordPressSharp.Constants.PostType.Page;

            wpc.NewPost(pos);`

it works perfectly till the last statment where it initiate this code
`   /// <summary>
        /// Creates a new entry in WordPress determined by Post.PostType to be a "Post", "Page", or custom post type
        /// </summary>
        /// <param name="post">The post to create</param>
        /// <returns></returns>
        public string NewPost(Post post)    
        {
            var post_put = new Post_Put();
            CopyPropertyValues(post, post_put);

            var terms = new XmlRpcStruct();

            if (post.Terms != null)
            {
                var termTaxes = post.Terms.GroupBy(t => t.Taxonomy);
                foreach (var grp in termTaxes)
                {
                    var termIds = grp.Select(g => g.Id).ToArray();
                    terms.Add(grp.Key, termIds);
                }

                post_put.Terms = terms;
            }
            if (post_put.PostType == "post" && String.IsNullOrEmpty(post_put.CommentStatus))
			{
				post_put.CommentStatus = "open";
			}

            return WordPressService.NewPost(WordPressSiteConfig.BlogId, WordPressSiteConfig.Username, WordPressSiteConfig.Password, post_put);
        }`

and it breaks saying "Method Not Allowed"  !!!

does that means Wordpress has changed there API Technic?
