### ISSUE TITLE
XmlRpcStruct key must be a string when add categories to post

### ISSUE THREAD

**Issue by Radzhab** [abrudtkuhl/WordPressSharp#57]
I have this code 

```
   var cat = client.GetCategories().Where(x => x.CategoryName == "STYLE").First();

            var termId = client.NewTerm(new Term
            {
                Name = "term name",
                Description = "term desc",
                Slug = "slug_term",
                Taxonomy = "post_tag"
            });



            Term[] t = new Term[2];
            t[0] = client.GetTerm("category", Convert.ToInt32(cat.Id)); // 4 is an existing category that was already being used...
            t[1] = new Term();
            t[1].Id = termId;


             var post = new Post
            {
                PostType = "post",
                Title = "Заголовок поста",
                Content = "<p>А это содержимое с тегами</p>",
                PublishDateTime = DateTime.Today.AddDays(-1),
                Status = "publish",
                FeaturedImageId = client.UploadFile(data).id,
                Terms = t,
            };
```

When i run it its return error
**XmlRpcStruct key must be a string.**

What i make wrong?

**Comment by sreedharloo** [comment]
Hi @Radzhab 
I too had the same issue. nothing wrong in the above code.
There is a change required in Category.cs class under Models directory.
You just need to declare Id and ParentId as 'int' (not string). After this change my code is working.

`public class Category
    {
        [XmlRpcMember("categoryId")]
        public int Id { get; set; }

        [XmlRpcMember("parentId")]
        public int ParentId { get; set; }

        [XmlRpcMember("categoryName")]
        public string CategoryName { get; set; }

        [XmlRpcMember("categoryDescription")]
        public string CategoryDescription { get; set; }

        [XmlRpcMember("description")]
        public string Description { get; set; }

        [XmlRpcMember("htmlUrl")]
        public string HtmlUrl { get; set; }

        [XmlRpcMember("rssUrl")]
        public string RssUrl { get; set; }
    }`

For more details please refer https://github.com/alexjamesbrown/JoeBlogs/issues/48

**Comment by abrudtkuhl** [comment]
@Sreedhar can you submit a Pull Request with this fix?

Andy Brudtkuhl
youmetandy.com

**Comment by abrudtkuhl** [comment]
FYI the GetCategories functionality has been removed from the library as the wp.getCategories method it was mapped to has been deprecated. The proper avenue is to use GetTerms()

https://codex.wordpress.org/XML-RPC_WordPress_API
