### ISSUE TITLE
Get File Link

### ISSUE THREAD

**Issue by guillogc** [abrudtkuhl/WordPressSharp#61]
Is there a way, having the post Id number of the uploaded image, to get the direct link to that image instead of the link for the post?

Thank you!!

**Comment by guillogc** [comment]
I found the solution myself.

It was using GetMediaItem instead of GetPost.

:)

**Comment by abrudtkuhl** [comment]
Was it an issue with code? Can you submit the fix via Pull Request?

**Comment by guillogc** [comment]
No no, no issue with the code. It was my issue. Thank you!!

**Comment by abrudtkuhl** [comment]
Excellent!
