### ISSUE TITLE
Custom Fields are not saved

### ISSUE THREAD

**Issue by miguelangelss4** [abrudtkuhl/WordPressSharp#66]
I'm having trouble with custom fields.

I have a new post with several values in customfields list, and I call NewPost function. The post is stored at database, but custom fields are not stored at postmeta table...

![image](https://cloud.githubusercontent.com/assets/15887424/22644036/44794a8a-ec61-11e6-8c22-cd382d290506.png)

**Comment by dmarklein** [comment]
I'm seeing the same thing. I'm trying to set the template for a page by setting the _wp_page_template meta field, but it's not making it into the database.

**Comment by miguelangelss4** [comment]
I want to add a CustomField to de customfields list, only to test that the problem is not a value with wrong serialization. I tried this:
NuevoPopup.CustomFields.ToList().Add(New WordPressSharp.Models.CustomField With {.Key = "msolla_prueba", .Value = "test"})

But it don't add anything. Can I add a customfield? how?

**Comment by miguelangelss4** [comment]
Is there any updates here?

**Comment by abrudtkuhl** [comment]
I will take a look this week. Planning some time to address a couple issues

**Comment by miguelangelss4** [comment]
Thanks you so much Andy, I wait for news.

**Comment by DUAB-Johan** [comment]
@dmarklein 
Wordpress does not allow changes to database-columns preceding with _ by default.
You have to add them to functions.php to allow the update:

function register_meta() {
    register_meta( 'post', '_description', '_meta_sanitize_cb', '_meta_yes_you_can');
}
add_action( 'init', 'register_meta' );

**Comment by miguelangelss4** [comment]
@DUAB-Johan hi
I'm seeing in [documentation](https://codex.wordpress.org/Function_Reference/register_meta) that this function (register_meta) only allow 3 parameters, and you had posted 4.

What are the values that you pass to register_meta? 
- The first one is clear that is the post_type
- Second one, I think is the meta key
- The 3 and 4, I don't know what are.

Anyway, my meta_key is popup_condition, it does not preceded by _... your answer is valid to me?
Thanks!

**Comment by miguelangelss4** [comment]
@abrudtkuhl, can you saw this issue? thanks!

**Comment by abrudtkuhl** [comment]
I believe this was fixed with #64
