### ISSUE TITLE
Support for asynchronous requests

### ISSUE THREAD

**Issue by simonhaga** [abrudtkuhl/WordPressSharp#69]
It would be really beneficial to have an option for asynchronous requests. I'm building a wpf application and on start-up I need to fetch categories and media items to fill the comboboxes with such information which delays the start-up by a number of seconds. Sure, Task is always an option, but it would be neat to have it built-in in the library to keep the code tidy.

**Comment by abrudtkuhl** [comment]
The XML-RPC.NET dependency used has support for async calls on proxy classes. I'd be interested in looking over a pull request adding async methods

http://xml-rpc.net/faq/xmlrpcnetfaq-3-0-0.html#2.8
