### ISSUE TITLE
Can't upload featured image, when using WordPressSharp in VB.NET

### ISSUE THREAD

**Issue by divyansheccentric** [abrudtkuhl/WordPressSharp#72]
Hi, I am developing a wordpress client for my blog. But I cant upload featured image to my post. The code works fine in C#. But shows an error in VB.NET
I am attaching a screenshot of error below.

![untitled](https://user-images.githubusercontent.com/32994707/31858508-f3aacbb6-b716-11e7-828d-e5d215530e21.png)

**Comment by divyansheccentric** [comment]
Anybody can reply a fix?

**Comment by abrudtkuhl** [comment]
Not sure on VB.Net, sorry!

Andy Brudtkuhl
https://youmetandy.com
________________________________

**Comment by divyansheccentric** [comment]
I figured out a solution, actually vb.net is not a case sensitive language so Id and id is same for vb.net that's why it gets confused while executing that part of code. We need to change Id to something else like IDDD etc.
Can you do this for me? Because you know your code better @abrudtkuhl

**Comment by abrudtkuhl** [comment]
I'm not sure what difference that would make for VB. You are free to change the library code locally if you need but I won't be changing it in the package. Thanks
________________________________
