### ISSUE TITLE
How to associate a category to a post WordPress?

### ISSUE THREAD

**Issue by manii-stack** [abrudtkuhl/WordPressSharp#75]
Hello Guys
For adding new category I used this guid
@KeesCBakker 
@1428245421 #48 (comment)

How about when I want to associate several categories to a post?(I created all categories in WordPress)
for instance 
main category>sub1>sub 2

**Comment by Blackcat156** [comment]
I have the same problem, and you can create an array
create Term
   Term[] term_cat = new Term[1];

term_cat [0]= client.GetTerm("category", “your category Id”);
/*If you have multiple categories, repeat the above steps into the array
*/

   var post = new Post
            {
                PostType = "post",
                Title = content_doc[0],
                FeaturedImageId = Cat_up.Id,
                PublishDateTime = DateTime.Now,
                **Terms = term_cat,**
                Status = "publish",
            };

**Comment by manii-stack** [comment]
thanks for your replay.
I did it and its work fine. but my program speed became so slowly!

**Comment by Blackcat156** [comment]
You can initialize a static variable.
Because the classification is rarely changed, I initialize the classification at the start of the release and keep it all the time.
